name: gocurl
description: "cURL action to perform REST API based on Go and net/http"
inputs:
  url: 
    description: 'The target URL'
  method:
    description: 'The request method, basically one of GET, POST, PUT, PATCH'
    default: "GET"
  accept:
    description: 'List of status codes to be accepted, else it is considerred to be failed'
    default: "200,201,204"
  headers:
    description: 'Headers object'
    default: "{}"
  params:
    description: 'Params object'
    default: "{}"
  body:
    description: 'Body object with string literal'
    default: "{}"
  timeout:
    description: 'Timeout (ms)'
    default: 1000
  basic-auth-token:
    description: 'Basic authentication token, format => username:password as base64'
    default: ""
  bearer-token: 
    description: 'Bearer Token'
    default: ""
  proxy-url:
    description: 'Proxy host, format => host:port'
    default: ""
  proxy-auth-token: 
    description: 'Proxy authentication username'
    default: ""
  proxy-auth-password: 
    description: 'Proxy authentication password'
    default: ""
  log-response: 
    description: 'Should log the response'
    default: 'false'
  retries:
    description: 'Number of retries'
    default: 1
outputs:
  response:
    description: 'The response object'
branding:
  icon: 'command'  
  color: 'gray-dark'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v4
    with:
      go-version: 'stable'
  - shell: bash
    run: |
      go run main.go \
      -url="${{ inputs.url }}" -method="${{ inputs.method }}" -accept="${{ inputs.accept }}" \
      -headers="${{ inputs.headers }}" -params="${{ inputs.params }}" -body="${{ inputs.body }}" \
      -timeout="${{ inputs.timeout }}" -basic-auth-token="${{ inputs.basic-auth-token }}" -bearer-token="${{ inputs.bearer-token }}" \
      -proxy-url="${{ inputs.proxy-url }}" -proxy-auth-username="${{ inputs.proxy-auth-username }}" -proxy-auth-password="${{ inputs.proxy-auth-password }}" \
      -log-response="${{ inputs.log-response }}" -retries="${{ inputs.retries }}"